### ISSUE TITLE
RuntimeError: error parsing trigger args for foreign key: ['']

### ISSUE THREAD

**Issue by atsaloli** [purcell/dbdoc#1]
Hello,

I tried using dbdoc with a Postgres 9.6.6 database and I get the error

    RuntimeError: error parsing trigger args for foreign key: ['']

Here is the session log, complete with traceback:
```
$ ./pgdbdoc.py -d pgdb 'localhost:cfdb:cfapache'  /tmp
Traceback (most recent call last):
  File "./pgdbdoc.py", line 61, in <module>
    main(sys.argv)
  File "./pgdbdoc.py", line 56, in main
    schema = dbdoc.pgschema.PostgresSchema(conn, 'postgres')
  File "/tmp/test/dbdoc/lib/dbdoc/pgschema.py", line 28, in __init__
    self._foreign_keys = _get_foreign_keys(conn)
  File "/tmp/test/dbdoc/lib/dbdoc/pgschema.py", line 148, in _get_foreign_keys
    % repr(tgargs)
RuntimeError: error parsing trigger args for foreign key: ['']
$
```

Meanwhile, Postgres log recorded this:

```
2018-08-20 20:33:13 GMT LOG:  could not receive data from client: Connection reset by peer
2018-08-20 20:33:13 GMT LOG:  unexpected EOF on client connection with an open transaction
```

I extracted the SQL query from `lib/dbdoc/pgschema.py` that dbdoc uses to find foreign keys by looking at triggers, and the code is expecting it to return 7 things but it's not 7 anymore:

```
cfdb=# SELECT pt.tgargs FROM pg_class pc,
        pg_proc pg_proc, pg_proc pg_proc_1, pg_trigger pg_trigger,
        pg_trigger pg_trigger_1, pg_proc pp, pg_trigger pt
  WHERE  pt.tgrelid = pc.oid AND pp.oid = pt.tgfoid
        AND pg_trigger.tgconstrrelid = pc.oid
        AND pg_proc.oid = pg_trigger.tgfoid
        AND pg_trigger_1.tgfoid = pg_proc_1.oid
        AND pg_trigger_1.tgconstrrelid = pc.oid
        AND ((pp.proname LIKE '%ins')
        AND (pg_proc.proname LIKE '%upd')
        AND (pg_proc_1.proname LIKE '%del')
        AND (pg_trigger.tgrelid=pt.tgconstrrelid)
        AND (pg_trigger_1.tgrelid = pt.tgconstrrelid))
;
 tgargs
--------
 \x
 \x
(2 rows)

cfdb=# 
```

**Comment by purcell** [comment]
There's probably a better way to find foreign keys these days - the dbdoc code is very old, and hasn't been updated for recent PostgreSQL versions, as you've discovered. I'll look at fixing this sometime if I can find time, but it probably won't be very soon. There are various better queries for this (see https://stackoverflow.com/questions/1152260/postgres-sql-to-list-table-foreign-keys).

**Comment by atsaloli** [comment]
Thank you @purcell 

I ended up using Schema Spy, thanks for mentioning it in your README

**Comment by purcell** [comment]
Yeah, Schema Spy is very nice!
